fail on failed unit tests

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,10 +52,16 @@ jobs:
         run: | 
           source env/bin/activate
           output=$(python -m unittest discover -s src -p *_test.py 2>&1)
-          echo "## Unit Tests" >> $GITHUB_STEP_SUMMARY
-          echo "<details><summary>Click to see unit test output</summary>" >> $GITHUB_STEP_SUMMARY
-          echo "$output">> $GITHUB_STEP_SUMMARY
-          echo "</details>" >> $GITHUB_STEP_SUMMARY
+          if [ $? -ne 0 ]; then
+            echo "## Unit Tests Failed" >> $GITHUB_STEP_SUMMARY
+            echo "$output">> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo "## Unit Tests" >> $GITHUB_STEP_SUMMARY
+            echo "<details><summary>Click to see unit test output</summary>" >> $GITHUB_STEP_SUMMARY
+            echo "$output">> $GITHUB_STEP_SUMMARY
+            echo "</details>" >> $GITHUB_STEP_SUMMARY
+          fi
 
   versions:
     name: Get all Deployed Versions
