updating workflows

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,5 +1,5 @@
 name: Build Image
-run-name: Build Image ${{ github.event.inputs.version }}
+run-name: Build Image ${{ inputs.version }}
 
 on:
   push:
@@ -51,7 +51,17 @@ jobs:
       - name: Run tests
         run: | 
           source env/bin/activate
-          python -m unittest discover -s src -p *_test.py    
+          output=$(python -m unittest discover -s src -p *_test.py 2>&1)
+          if [ $? -ne 0 ]; then
+            echo "## Unit Tests Failed" >> $GITHUB_STEP_SUMMARY
+            echo "$output">> $GITHUB_STEP_SUMMARY
+            exit 1
+          else
+            echo "## Unit Tests" >> $GITHUB_STEP_SUMMARY
+            echo "<details><summary>Click to see unit test output</summary>" >> $GITHUB_STEP_SUMMARY
+            echo "$output">> $GITHUB_STEP_SUMMARY
+            echo "</details>" >> $GITHUB_STEP_SUMMARY
+          fi
 
   versions:
     name: Get all Deployed Versions
@@ -88,25 +98,29 @@ jobs:
       - name: JSON Output
         id: json_output
         run: |
-          cache_updates=$(python - <<EOF
+          updates=$(python - <<EOF
           import json
-          cache_updates = []
-          if "${{ inputs.version }}" != "":
-            if "${{ inputs.version }}" == "${{ steps.get_dev_version.outputs.version }}":
-              cache_updates.append({"env": "dev", "version": "${{ steps.get_dev_version.outputs.version }}"})
-            if "${{ inputs.version }}" == "${{ steps.get_test_version.outputs.version }}":
-              cache_updates.append({"env": "test", "version": "${{ steps.get_test_version.outputs.version }}"})
-            if "${{ inputs.version }}" == "${{ steps.get_stage_version.outputs.version }}":
-              cache_updates.append({"env": "stage", "version": "${{ steps.get_stage_version.outputs.version }}"})
-            if "${{ inputs.version }}" == "${{ steps.get_prod_version.outputs.version }}":
-              cache_updates.append({"env": "prod", "version": "${{ steps.get_prod_version.outputs.version }}"})
-          print(json.dumps(cache_updates))
+          updates = []
+          if "${{ steps.get_dev_version.outputs.version }}" != "":
+            if "${{ inputs.version }}" == "${{ steps.get_dev_version.outputs.version }}" or "${{ inputs.version }}" == "":
+              updates.append({"env": "dev", "version": "${{ steps.get_dev_version.outputs.version }}"})
+            if "${{ inputs.version }}" != "":
+              if "${{ inputs.version }}" == "${{ steps.get_test_version.outputs.version }}":
+                updates.append({"env": "test", "version": "${{ steps.get_test_version.outputs.version }}"})
+              if "${{ inputs.version }}" == "${{ steps.get_stage_version.outputs.version }}":
+                updates.append({"env": "stage", "version": "${{ steps.get_stage_version.outputs.version }}"})
+              if "${{ inputs.version }}" == "${{ steps.get_prod_version.outputs.version }}":
+                updates.append({"env": "prod", "version": "${{ steps.get_prod_version.outputs.version }}"})
+          print(json.dumps(updates))
           EOF
           ) 
-          echo "cache_updates=$cache_updates">> $GITHUB_OUTPUT
+          echo "## Updates" >> $GITHUB_STEP_SUMMARY
+          echo "$updates">> $GITHUB_STEP_SUMMARY
+          echo "updates=$updates">> $GITHUB_OUTPUT
     outputs:
       dev: ${{ steps.get_dev_version.outputs.version }}
-      cache_updates: ${{ steps.json_output.outputs.cache_updates }}
+      prod: ${{ steps.get_prod_version.outputs.version }}
+      updates: ${{ steps.json_output.outputs.updates }}
 
   build:
     name: Build Code ${{ inputs.version }}
@@ -140,26 +154,26 @@ jobs:
           docker push artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates:${{ steps.which_version.outputs.version }}
 
 
-  deploy:
-    name: Deploy to Dev
-    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
-    needs: [versions, build]
-    uses: ./.github/workflows/deploy.yml
-    with: 
-      version: ${{ needs.versions.outputs.dev }}
-      environment: dev
-    secrets: inherit
-
-  cache_deploys:
-    name: Cache Deploys
-    if: github.event_name == 'workflow_dispatch' && needs.versions.outputs.cache_updates != '[]'
+  deploys:
+    name: Deploys
+    if: needs.versions.outputs.updates != '[]'
     needs: [versions, build]
     strategy:
       fail-fast: false
       matrix:
-        versions: ${{ fromJson(needs.versions.outputs.cache_updates) || '[]' }}
+        versions: ${{ fromJson(needs.versions.outputs.updates) || '[]' }}
     uses: ./.github/workflows/deploy.yml
     with: 
       version: ${{ matrix.versions.version }}
       environment: ${{ matrix.versions.env }}
+    secrets: inherit
+
+
+  test_production:
+    name: Test Production
+    if: needs.versions.outputs.prod != ''
+    needs: [versions, deploys]
+    uses: ./.github/workflows/test_instances.yml
+    with:
+      environment: prod
     secrets: inherit
