updating the build and deploy scripts

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,23 +1,16 @@
-name: Deploy
+name: Deploy Runtime
 on:
   # push:
   #   branches: [ dev ]
   workflow_dispatch:
     inputs:
-      from_tag:
-        type: choice
-        default: 'latest'
-        options:
-          - 'latest'
-          - 'dev'
-          - 'test'
-          - 'stage'
-          - 'prod'
+      version:
+        type: string
         required: true
-      environment: 
+      environment:
         type: choice
         default: 'dev'
-        options:
+        options: 
           - 'dev'
           - 'test'
           - 'stage'
@@ -25,6 +18,7 @@ on:
         required: true
 
 env:
+  version: ${{ github.event.inputs.version }}
   AWS_REGION: us-east-1
 
 defaults:
@@ -33,7 +27,7 @@ defaults:
 
 jobs:
   deploy:
-    name: Deploy ${{ github.event.inputs.environment }}
+    name: Deploy to ${{ github.event.inputs.environment }}
     runs-on: ubuntu-latest
 
     steps:
@@ -45,18 +39,11 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NONPROD }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NONPROD }}
           aws-region: ${{ env.AWS_REGION }}
-          # Note: the aais-ecs-deploy-action will be assuming a role for the deploy
-          #       just leaving this commented code here for future me
-          # role-to-assume: 'arn:aws:iam::${{ env.account }}:role/AutomationDeployRole'
-          # role-duration-seconds: 1200
-          # role-session-name: PersonUpdatesDeploySession
-          # role-skip-session-tagging: true
-          # role-external-id: ${{ secrets.EXTERNAL_ID }}
 
       - name: Checkout
         uses: actions/checkout@v3
         with:
-          path: ./salesforce-person-updates
+          path: ./salesforce
 
       # Checking out the cluster config to provide it for the Deploy Action
       - name: Checkout cluster config
@@ -65,22 +52,36 @@ jobs:
           repository: HUIT/aais-services-config
           path: ./aais-services-config
 
-      - name: Check if ${{ github.event.inputs.from_tag }} exists
+      - name: Login to artifactory
         run: |
-          echo "Pull old image and store it in case of rollback"
-          docker pull artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates:${{ github.event.inputs.environment }}
-          docker tag artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates:${{ github.event.inputs.environment }} artifactory.huit.harvard.edu/person-updates:temp
-        continue-on-error: true
-
-      - name: Move tags from ${{ github.event.inputs.from_tag }} to ${{ github.event.inputs.environment }}
+          docker login artifactory.huit.harvard.edu --username "${{ secrets.ARTIFACTORY_USER }}" --password "${{ secrets.ARTIFACTORY_PWD }}"
+  
+      # Note: this will get the version from the ansible vars
+      - name: Get Version from ansible_vars
         run: |
-          echo "Pull new image and rename it"
-          docker pull artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates:${{ github.event.inputs.from_tag }}
-          docker tag artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates:${{ github.event.inputs.from_tag }} artifactory.huit.harvard.edu/aais-docker-local/person-updates:${{ github.event.inputs.environment }}
-          docker push artifactory.huit.harvard.edu/aais-docker-local/salesforce-person-updates:${{ github.event.inputs.environment }}
+          cd salesforce
+          while read -r line; do
+            if [[ $line =~ "target_app_version" ]] && ! [[ $line =~ ^#.* ]]; then
+            # delete everything up to the opening double quote
+            version="${line#*\"}"
+            # delete everything after the next double quote
+            version="${version%%\"*}"
+          fi
+          done < ./ansible_vars/${{ github.event.inputs.environment }}_ansible_vars.yml
 
+          if [[ $version -ne ${{ env.version }} ]]; then
+            echo "Error: version does not match in ansible_vars"
+            exit 1
+          fi
+
+
+      # this will fail if the manifest doesn't exist
+      - name: Check if image exists
+        run: |          
+          docker manifest inspect artifactory.huit.harvard.edu/ats-docker/salesforce-person-updates:$version
+          
       - name: Run AAIS Deploy Container Action
-        uses: HUIT/aais-ecs-deploy-action@HEAD
+        uses: HUIT/aais-ecs-deploy-action@v1.0.1
         with:
           # Required
           common_config: aais-services-config/aais_services_${{ github.event.inputs.environment }}.yml
@@ -89,10 +90,5 @@ jobs:
           # Optional
           #   this needs to match the directory the main repository was checked out into
           #   if the checkout was done without a path, this is not needed
-          app_root: salesforce-person-updates
- 
-      - name: Rollback image on Error
-        if: ${{ failure() }}
-        run: | 
-          docker tag artifactory.huit.harvard.edu/aais-docker-local/person-updates:temp artifactory.huit.harvard.edu/person-updates:${{ github.event.inputs.environment }}
-          docker push artifactory.huit.harvard.edu/aais-docker-local/person-updates:${{ github.event.inputs.environment }}
+          app_root: salesforce
+     
