using action for waiting

diff --git a/.github/workflows/full_data_load.yml b/.github/workflows/full_data_load.yml
--- a/.github/workflows/full_data_load.yml
+++ b/.github/workflows/full_data_load.yml
@@ -37,26 +37,26 @@ on:
         options:
           - 'True'
           - 'False'
-      cpu:
-        type: choice
-        required: false
-        default: '1024'
-        options:
-          - '1024'
-          - '2048'
-      memory:
-        type: choice
-        required: false
-        default: '4096'
-        options:
-          - '2048'
-          - '3072'
-          - '4096'
-          - '5120'
-          - '6144'
-          - '7168'
-          - '8192'
-          - '16384'
+      # cpu:
+      #   type: choice
+      #   required: false
+      #   default: '1024'
+      #   options:
+      #     - '1024'
+      #     - '2048'
+      # memory:
+      #   type: choice
+      #   required: false
+      #   default: '4096'
+      #   options:
+      #     - '2048'
+      #     - '3072'
+      #     - '4096'
+      #     - '5120'
+      #     - '6144'
+      #     - '7168'
+      #     - '8192'
+      #     - '16384'
                             
 defaults:
   run:
@@ -86,75 +86,106 @@ jobs:
       - name: get current identity 
         run: aws sts get-caller-identity
 
-      - name: Create Overrides
-        run: |
-          CONTAINER_OVERRIDES='[ 
-            {
-              "name": "aais-services-${{ inputs.environment }}-feed-salesforce-person-updates", 
-              "cpu": ${{ inputs.cpu }},
-              "memory": ${{ inputs.memory }},
-              "environment": [ 
-                {
-                  "name": "SALESFORCE_INSTANCE_ID", 
-                  "value": "${{ inputs.salesforce_instance_id }}"
-                }, {
-                  "name": "TABLE_NAME", 
-                  "value": "${{ vars.TABLE_NAME }}"
-                }, {
-                  "name": "action", 
-                  "value": "full-person-load"
-                }, {
-                  "name": "BATCH_SIZE", 
-                  "value": "${{ inputs.batch_size }}"
-                }, {
-                  "name": "BATCH_THREAD_COUNT", 
-                  "value": "${{ inputs.batch_thread_count }}"
-                }, {
-                  "name": "RECORD_LIMIT", 
-                  "value": "${{ inputs.record_limit }}"
-                }, {
-                  "name": "DEBUG", 
-                  "value": "${{ inputs.debug }}"
-                }
-              ]
-            } 
-          ]'
-          CONTAINER_OVERRIDES=$(echo "$CONTAINER_OVERRIDES" | tr -d '\n')
-          echo "CONTAINER_OVERRIDES=$CONTAINER_OVERRIDES" >> $GITHUB_ENV
+      # - name: Create Overrides
+      #   run: |
+      #     CONTAINER_OVERRIDES='[ 
+      #       {
+      #         "name": "aais-services-${{ inputs.environment }}-feed-salesforce-person-updates", 
+      #         "cpu": ${{ inputs.cpu }},
+      #         "memory": ${{ inputs.memory }},
+      #         "environment": [ 
+      #           {
+      #             "name": "SALESFORCE_INSTANCE_ID", 
+      #             "value": "${{ inputs.salesforce_instance_id }}"
+      #           }, {
+      #             "name": "TABLE_NAME", 
+      #             "value": "${{ vars.TABLE_NAME }}"
+      #           }, {
+      #             "name": "action", 
+      #             "value": "full-person-load"
+      #           }, {
+      #             "name": "BATCH_SIZE", 
+      #             "value": "${{ inputs.batch_size }}"
+      #           }, {
+      #             "name": "BATCH_THREAD_COUNT", 
+      #             "value": "${{ inputs.batch_thread_count }}"
+      #           }, {
+      #             "name": "RECORD_LIMIT", 
+      #             "value": "${{ inputs.record_limit }}"
+      #           }, {
+      #             "name": "DEBUG", 
+      #             "value": "${{ inputs.debug }}"
+      #           }
+      #         ]
+      #       } 
+      #     ]'
+      #     CONTAINER_OVERRIDES=$(echo "$CONTAINER_OVERRIDES" | tr -d '\n')
+      #     echo "CONTAINER_OVERRIDES=$CONTAINER_OVERRIDES" >> $GITHUB_ENV
 
       - name: Run ${{ inputs.environment }} full data load
-        run: |
-          TASK_ARN=$(aws ecs run-task \
-            --cluster aais-services-${{ inputs.environment }}-cluster \
-            --overrides '{"cpu": "${{ inputs.cpu }}", "memory": "${{ inputs.memory }}", "containerOverrides": ${{ env.CONTAINER_OVERRIDES }} }' \
-            --task-definition arn:aws:ecs:us-east-1:${{ vars.AWS_ACCOUNT }}:task-definition/aais-services-${{ inputs.environment }}-feed-salesforce-person-updates \
-            --network-configuration '{ "awsvpcConfiguration": { "assignPublicIp":"DISABLED", "securityGroups": ["${{ vars.SECURITY_GROUP }}"], "subnets": ["${{ vars.SUBNET }}"]}}' \
-            --launch-type FARGATE \
-            --query 'tasks[0].taskArn' \
-            --output text)
-          echo "TASK_ARN=$TASK_ARN" >> $GITHUB_ENV
-          echo "## Task ARN" >> $GITHUB_STEP_SUMMARY
-          echo "$TASK_ARN" >> $GITHUB_STEP_SUMMARY
+        uses: HUIT/aais-ecs-infrastructure/actions/run-task@develop
+        env:
+          CLUSTER: aais-services-${{ inputs.environment || 'dev' }}-cluster
+          TASK_DEF_ARN: arn:aws:ecs:us-east-1:${{ vars.AWS_ACCOUNT }}:task-definition/aais-services-${{ inputs.environment || 'dev' }}-feed-salesforce-person-updates
+          CONTAINER_NAME: aais-services-${{ inputs.environment || 'dev' }}-feed-salesforce-person-updates
+          ENVIRONMENT: ${{ inputs.environment || 'dev' }}
+          SUBNETS: '["${{ vars.SUBNET }}"]'
+          SECURITY_GROUPS: '["${{ vars.SECURITY_GROUP }}"]'
+        with:
+          cluster: ${{ env.CLUSTER}}
+          task_def_arn: ${{ env.TASK_DEF_ARN}}
+          container_name: ${{ env.CONTAINER_NAME }}
+          # FUTURE ME: if you're feeling adventurous, try using the > or | to make this more readable
+          override_fields: > 
+            {
+              "SALESFORCE_INSTANCE_ID": "${{ inputs.salesforce_instance_id }}",
+              "TABLE_NAME": "${{ vars.TABLE_NAME }}",
+              "action": "single-person-update", 
+              "BATCH_SIZE": "${{ inputs.batch_size }}",
+              "BATCH_THREAD_COUNT": "${{ inputs.batch_thread_count }}",
+              "RECORD_LIMIT": "${{ inputs.record_limit }}",
+              "DEBUG": "${{ inputs.debug }}"
+            }
+          subnets: ${{ env.SUBNETS }}
+          security_groups: ${{ env.SECURITY_GROUPS }}
+          print_summary: true
+          debug: true
+          wait: true
+
+
+      # - name: Run ${{ inputs.environment }} full data load
+      #   run: |
+      #     TASK_ARN=$(aws ecs run-task \
+      #       --cluster aais-services-${{ inputs.environment }}-cluster \
+      #       --overrides '{"cpu": "${{ inputs.cpu }}", "memory": "${{ inputs.memory }}", "containerOverrides": ${{ env.CONTAINER_OVERRIDES }} }' \
+      #       --task-definition arn:aws:ecs:us-east-1:${{ vars.AWS_ACCOUNT }}:task-definition/aais-services-${{ inputs.environment }}-feed-salesforce-person-updates \
+      #       --network-configuration '{ "awsvpcConfiguration": { "assignPublicIp":"DISABLED", "securityGroups": ["${{ vars.SECURITY_GROUP }}"], "subnets": ["${{ vars.SUBNET }}"]}}' \
+      #       --launch-type FARGATE \
+      #       --query 'tasks[0].taskArn' \
+      #       --output text)
+      #     echo "TASK_ARN=$TASK_ARN" >> $GITHUB_ENV
+      #     echo "## Task ARN" >> $GITHUB_STEP_SUMMARY
+      #     echo "$TASK_ARN" >> $GITHUB_STEP_SUMMARY
   
-      # Note: stoppedReason needs to be last in the read list as it may contain spaces
-      - name: Wait for task to complete
-        run: |
-          while true; do     
-            read lastStatus stopCode exitCode stoppedReason <<< $(aws ecs describe-tasks --cluster aais-services-${{ inputs.environment }}-cluster --tasks ${{ env.TASK_ARN }} --query 'tasks[0].[lastStatus, stopCode, containers[0].exitCode, stoppedReason]' --output text)
-            if [[ "$stopCode" == "EssentialContainerExited" || "$stopCode" == "UserInitiated" ]]; then
-              if [[ "$exitCode" != "None" ]]; then
-                echo "Task failed with exit code $exitCode with reason: $stoppedReason"
-                echo "Task failed with exit code $exitCode with reason: $stoppedReason" >> $GITHUB_STEP_SUMMARY
-                exit 1
-              else
-                echo "Task completed successfully. $stoppedReason"
-                echo "Task completed successfully. $stoppedReason" >> $GITHUB_STEP_SUMMARY
-                exit 0
-              fi
-              elif [[ "$lastStatus" == "STOPPED" ]]; then
-                echo "Task stopped with stop code $stopCode with reason: $stoppedReason and exit code: $exitCode"
-                echo "Task stopped with stop code $stopCode with reason: $stoppedReason and exit code: $exitCode" >> $GITHUB_STEP_SUMMARY
-              exit 1
-            fi
-            sleep 10
-          done
+      # # Note: stoppedReason needs to be last in the read list as it may contain spaces
+      # - name: Wait for task to complete
+      #   run: |
+      #     while true; do     
+      #       read lastStatus stopCode exitCode stoppedReason <<< $(aws ecs describe-tasks --cluster aais-services-${{ inputs.environment }}-cluster --tasks ${{ env.TASK_ARN }} --query 'tasks[0].[lastStatus, stopCode, containers[0].exitCode, stoppedReason]' --output text)
+      #       if [[ "$stopCode" == "EssentialContainerExited" || "$stopCode" == "UserInitiated" ]]; then
+      #         if [[ "$exitCode" != "None" ]]; then
+      #           echo "Task failed with exit code $exitCode with reason: $stoppedReason"
+      #           echo "Task failed with exit code $exitCode with reason: $stoppedReason" >> $GITHUB_STEP_SUMMARY
+      #           exit 1
+      #         else
+      #           echo "Task completed successfully. $stoppedReason"
+      #           echo "Task completed successfully. $stoppedReason" >> $GITHUB_STEP_SUMMARY
+      #           exit 0
+      #         fi
+      #         elif [[ "$lastStatus" == "STOPPED" ]]; then
+      #           echo "Task stopped with stop code $stopCode with reason: $stoppedReason and exit code: $exitCode"
+      #           echo "Task stopped with stop code $stopCode with reason: $stoppedReason and exit code: $exitCode" >> $GITHUB_STEP_SUMMARY
+      #         exit 1
+      #       fi
+      #       sleep 10
+      #     done
